### ISSUE TITLE
Open datasets availability towards application that leverage COVESA VISS APIs

### ISSUE THREAD

**Issue by renjithrajagopal-sudo** [COVESA/vissr#30]
For developers to use application that use COVESA VISS APIs & data recording, following shall be addressed

- Vehicle dataset availability of different drive scenarios  in RemotiveLabs cloud with VSS mapping

Configure VSS, VISSR/feeder to support towards Open datasets in free version : https://cloud.remotivelabs.com

**Comment by slawr** [comment]
Hi Renjith, this general topic of open data sets we are also discussing in the COVESA Central Data Service Playground. Longer story short we see the value of some data sets at rest than can be loaded into various COVESA projects. I had some discussion about this with RemotiveLabs as well prior to and at the AMM.

It would be good if we can identify some common requirements and increase the resources working on that core aspect for reuse downstream.

**Comment by renjithrajagopal-sudo** [comment]
@slawr  Sure ! Above datasets caters uni-directional use case(READ-only) especially towards AAOS or VISS. Datasets are not subjected to VSS mapping yet which is WIP from RemotiveLabs. Initial VSS mapping will be done to satisfy following sample use case.

https://github.com/COVESA/vissr/tree/master/client/android

**Comment by renjithrajagopal-sudo** [comment]
@slawr  @petervolvowinz  Do we have use cases & requirements somewhere documented ?

**Comment by renjithrajagopal-sudo** [comment]
VSS translated open datasets available here : https://cloud.remotivelabs.com/

**Comment by slawr** [comment]
> @slawr @petervolvowinz Do we have use cases & requirements somewhere documented ?

Sorry @renjithrajagopal-sudo I missed these posts somehow.

There has been scattered comments in AMM presentations and elsewhere but I would say somewhat of a dearth of more detailed descriptions. I always hoped that the OEMs and Tier 1s would step up with some top down logical descriptions of cases/requirements, 'we would like to down sample at the Edge from X to Y, with compression efficiency A'.

I expect some bottom up descriptions to fall out of some of the work we are doing in the Data Architecture group. For example BMW work on the knowledge layer connector will result in some knowledge reasoning rules that will need data.

The most concrete collection of requirements I am aware of currently is the Guidelines document draft in the Commercial Vehicles group. The cases are orientated towards telemetrics and fleet, but there are concrete figures.
